### PR TITLE
Feature/contract call

### PR DESCRIPTION
**Pull request by sirius651**
finish & verified to call contract both reading & executing tx.
it includes refactored extrinsic call & ecdsa account as well

### CODE REVIEW

**Comment by hoonsubin** [comment]
@sirius651 

I'm getting an error when I'm trying to deploy an ink contract

```
ModalCreateDapps.vue?17d3:155 _onFailed CodeSubmittableResult
_onFailedTx @ ModalCreateDapps.vue?17d3:155
assert.js?4a9d:24 Uncaught Error: Cannot convert 'Module' via asOther
    at assert (assert.js?4a9d:24)
    at Proxy.get (Enum.js?bf1f:206)
    at Reflect.get (<anonymous>)
    at Object.get (reactivity.esm-bundler.js?0a2b:428)
    at traverse (runtime-core.esm-bundler.js?9e79:7507)
    at traverse (runtime-core.esm-bundler.js?9e79:7507)
    at traverse (runtime-core.esm-bundler.js?9e79:7507)
    at traverse (runtime-core.esm-bundler.js?9e79:7507)
    at traverse (runtime-core.esm-bundler.js?9e79:7507)
    at ReactiveEffect.getter [as fn] (runtime-core.esm-bundler.js?9e79:7356)
```
Screen Shot 2021-09-23 at 10 05 48 AM

This is the contract file I used.

[erc721.zip](https://github.com/PlasmNetwork/astar-apps/files/7215915/erc721.zip)

**Comment by sirius651** [comment]
FYI, in my environment,
`flipper.contract`
[flipper.contract.zip](https://github.com/PlasmNetwork/astar-apps/files/7217307/flipper.contract.zip)

in dusty network,
Endowment: 26 PLD
Max gas allowed:  200 nano

it successfully deployed well.

**Comment by sirius651** [comment]
Also, when I tried to `erc721` contract, 

at same option above,

in dusty network,
Endowment: 26 PLD
Max gas allowed: 200 nano

it successfully deployed as well.

@hoonsubin  what's your status of `Endowment` & `Max gas allowed` ?

**Comment by hoonsubin** [comment]
> Also, when I tried to `erc721` contract,
> 
> at same option above,
> 
> in dusty network,
> Endowment: 26 PLD
> Max gas allowed: 200 nano
> 
> it successfully deployed as well.
> 
> @hoonsubin what's your status of `Endowment` & `Max gas allowed` ?

I tried `Endowmwnt` of 4 PLD and 14 PLD on my previous test. Putting 26 PLD as the `Endowment` does allow me to deploy the contract without issue. thank you.

Can we make the following improvements?

1. calculate the ideal `Endowment` for the contract so it's provided by default.
2. show a helpful error message so that the user can see what the issue is?

**Comment by sirius651** [comment]
> Can we make the following improvements?
> 
> 1. calculate the ideal `Endowment` for the contract so it's provided by default.
> 2. show a helpful error message so that the user can see what the issue is?

Set required endowment as default before moving to step2 if the endowment is less than required one

**Review by hoonsubin — APPROVED** [review]
LGTM

**Pull request merged**
